services:
  postgres:
    image: postgres:15
    container_name: finanzas_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finanzas_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  init_db:
    build: .
    container_name: finanzas_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    command: >
      sh -c "
        python Script/plazoFijo_api_ETL.py &&
        python Script/DOLAR_AHORA_ETL.py &&
        python Script/DOLAR_hist_ETL.py &&
        python Script/INFLACION_api_ETL.py &&
        python Script/FCI_api_ETL.py
      "
    networks:
      - finanzas_network

  dashboard:
    build: .
    container_name: finanzas_dashboard
    depends_on:
      - init_db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    networks:
      - finanzas_network

volumes:
  postgres_data:

networks:
  finanzas_network:
    driver: bridge